#ifndef VF2_HYBRID_BRIDGE_H
#define VF2_HYBRID_BRIDGE_H

#include <stddef.h>
#include <stdint.h>

#include "vf2/i960/executor.h"
#include "vf2/model2a.h"
#include "vf2/status.h"

typedef enum vf2_hybrid_bridge_kind {
    VF2_HYBRID_BRIDGE_NONE = 0,
    VF2_HYBRID_BRIDGE_TEXTURE_BYTE_RUN,
    VF2_HYBRID_BRIDGE_TEXTURE_BYTE_DECODE,
    VF2_HYBRID_BRIDGE_TEXTURE_WORD_RUN,
    VF2_HYBRID_BRIDGE_TEXTURE_WORD_DECODE,
    VF2_HYBRID_BRIDGE_TEXTURE_SYMBOL_TABLE_BUILD,
    VF2_HYBRID_BRIDGE_TEXTURE_PAIR_TABLE_BUILD,
    VF2_HYBRID_BRIDGE_TEXTURE_TREE_DISPATCH,
    VF2_HYBRID_BRIDGE_TEXTURE_TREE_EXPAND,
    VF2_HYBRID_BRIDGE_TEXTURE_WORD_PREPARE,
    VF2_HYBRID_BRIDGE_TEXTURE_COLOR_PREPARE,
    VF2_HYBRID_BRIDGE_TEXTURE_COLOR_CONVERT,
    VF2_HYBRID_BRIDGE_TEXTURE_ADDRESS_TABLE,
    VF2_HYBRID_BRIDGE_DIAGNOSTIC_TEXT_COPY,
    VF2_HYBRID_BRIDGE_TILE_GLYPH_EXPAND,
    VF2_HYBRID_BRIDGE_VIDEO_STATUS_LATCH,
    VF2_HYBRID_BRIDGE_GEOMETRY_FRAME_COMMIT,
    VF2_HYBRID_BRIDGE_GEOMETRY_COMMAND_SETUP,
    VF2_HYBRID_BRIDGE_FRAME_SCRATCH_CLEAR,
    VF2_HYBRID_BRIDGE_COLOR_TABLE_REBUILD,
    VF2_HYBRID_BRIDGE_DISPLAY_COLOR_PROFILE_APPLY,
    VF2_HYBRID_BRIDGE_DISPLAY_PROFILE_UNIT_FILL,
    VF2_HYBRID_BRIDGE_DISPLAY_PROFILE_MODE_CONSTANTS,
    VF2_HYBRID_BRIDGE_DISPLAY_PROFILE_APPLY,
    VF2_HYBRID_BRIDGE_VIDEO_COMMAND_SUBMIT,
    VF2_HYBRID_BRIDGE_VIDEO_TABLE_EXPAND_128,
    VF2_HYBRID_BRIDGE_DISPLAY_TRANSFORM_DEFAULTS,
    VF2_HYBRID_BRIDGE_DISPLAY_RUNTIME_INITIALIZE,
    VF2_HYBRID_BRIDGE_PALETTE_PAGE_UPLOAD,
    VF2_HYBRID_BRIDGE_TEXTURE_CONVERT_LOOP,
    VF2_HYBRID_BRIDGE_TEXTURE_CONVERT_POST,
    VF2_HYBRID_BRIDGE_TIMER_WAIT_UPDATE,
    VF2_HYBRID_BRIDGE_INLINE_TEXT_THUNK,
    VF2_HYBRID_BRIDGE_TEXTURE_STATUS_LINE,
    VF2_HYBRID_BRIDGE_GAME_STATE_CLASSIFY,
    VF2_HYBRID_BRIDGE_GAME_COLOR_LOOKUP,
    VF2_HYBRID_BRIDGE_GAME_THRESHOLD_EVALUATE,
    VF2_HYBRID_BRIDGE_GAME_METER_UPDATE,
    VF2_HYBRID_BRIDGE_GAME_INPUT_UPDATE,
    VF2_HYBRID_BRIDGE_GAME_STATE_UPDATE,
    VF2_HYBRID_BRIDGE_TILE_CONTROLLER_UPDATE,
    VF2_HYBRID_BRIDGE_FRAME_TIMER_PREFIX,
    VF2_HYBRID_BRIDGE_INTERRUPT_SAVE_PREFIX,
    VF2_HYBRID_BRIDGE_INTERRUPT_BUFFER_GATE,
    VF2_HYBRID_BRIDGE_INTERRUPT_INPUT_RING,
    VF2_HYBRID_BRIDGE_INTERRUPT_RESTORE_PREFIX,
    VF2_HYBRID_BRIDGE_FRAME_TIMER_SUFFIX,
    VF2_HYBRID_BRIDGE_TEXTURE_STATUS_TAIL,
    VF2_HYBRID_BRIDGE_INTERRUPT_PLAYER_LAYER,
    VF2_HYBRID_BRIDGE_INTERRUPT_GAME_INPUT,
    VF2_HYBRID_BRIDGE_INTERRUPT_GAME_STATE,
    VF2_HYBRID_BRIDGE_INTERRUPT_TILE_SYNC,
    VF2_HYBRID_BRIDGE_MAIN_POST_TIMER,
    VF2_HYBRID_BRIDGE_MAIN_CLEAR_PREFIX,
    VF2_HYBRID_BRIDGE_MAIN_FINAL_CLUSTER,
    VF2_HYBRID_BRIDGE_MAIN_GEOMETRY_PREFIX,
    VF2_HYBRID_BRIDGE_MAIN_TEXTURE_ORCHESTRATOR_CALL,
    VF2_HYBRID_BRIDGE_MAIN_FRAME_TIMER_CALL,
    VF2_HYBRID_BRIDGE_INTERRUPT_INITIAL_CLUSTER,
    VF2_HYBRID_BRIDGE_FRAME_WAIT_POLL,
    VF2_HYBRID_BRIDGE_INTERRUPT_RETURN_WAIT_EXIT,
    VF2_HYBRID_BRIDGE_SYSTEM_MEMORY_DIAGNOSTIC,
    VF2_HYBRID_BRIDGE_VIDEO_INPUT_SYNC,
    VF2_HYBRID_BRIDGE_FRAME_COUNTER_ADVANCE,
    VF2_HYBRID_BRIDGE_FRAME_PHASE_ADVANCE,
    VF2_HYBRID_BRIDGE_FRAME_SHADOW_VERIFY,
    VF2_HYBRID_BRIDGE_FRAME_BUFFER_GATE,
    VF2_HYBRID_BRIDGE_FRAME_DISPATCH_TICK,
    VF2_HYBRID_BRIDGE_FRAME_GEOMETRY_GATE,
    VF2_HYBRID_BRIDGE_VIDEO_REGISTER_COMPOSE,
    VF2_HYBRID_BRIDGE_VIDEO_INPUT_LATCH_WRITE,
    VF2_HYBRID_BRIDGE_PLAYER_UPDATE_GATE,
    VF2_HYBRID_BRIDGE_VIDEO_LAYER_COMMIT,
    VF2_HYBRID_BRIDGE_INPUT_BIT0_SEQUENCE_GATE,
    VF2_HYBRID_BRIDGE_INPUT_BIT1_SEQUENCE_GATE,
    VF2_HYBRID_BRIDGE_INPUT_RING_POLL,
    VF2_HYBRID_BRIDGE_TILE_RUNTIME_GATE,
    VF2_HYBRID_BRIDGE_GAME_EVENT_QUEUE_WRITE,
    VF2_HYBRID_BRIDGE_TEXTURE_MAINTENANCE,
    VF2_HYBRID_BRIDGE_TEXTURE_UPLOAD_DISPATCH,
    VF2_HYBRID_BRIDGE_TEXTURE_ORCHESTRATOR_ENTRY_GATE,
    VF2_HYBRID_BRIDGE_TEXTURE_RECORD_STATUS_SETUP,
    VF2_HYBRID_BRIDGE_TEXTURE_STREAM_HEADER_CALL,
    VF2_HYBRID_BRIDGE_TEXTURE_ORCHESTRATOR_SAVE_CALL,
    VF2_HYBRID_BRIDGE_TEXTURE_FRAME_GATE_CALL,
    VF2_HYBRID_BRIDGE_TEXTURE_DEFAULT_LIMITS,
    VF2_HYBRID_BRIDGE_TEXTURE_STATUS_DISPATCH_CALL,
    VF2_HYBRID_BRIDGE_TEXTURE_ACTIVE_PREPARE_CALL,
    VF2_HYBRID_BRIDGE_TEXTURE_HEADER_DECODE,
    VF2_HYBRID_BRIDGE_TEXTURE_STATUS_SCAN_END,
    VF2_HYBRID_BRIDGE_TEXTURE_CHILD_GATE_A,
    VF2_HYBRID_BRIDGE_TEXTURE_CHILD_GATE_B,
    VF2_HYBRID_BRIDGE_TEXTURE_LOOP_GATE,
    VF2_HYBRID_BRIDGE_TEXTURE_RECORD_ADVANCE,
    VF2_HYBRID_BRIDGE_TEXTURE_FINAL_STATUS_CALL,
    VF2_HYBRID_BRIDGE_TEXTURE_BODY_RETURN,
    VF2_HYBRID_BRIDGE_TEXTURE_POST_BODY_CALL,
    VF2_HYBRID_BRIDGE_TEXTURE_COUNTER_UPDATE,
    VF2_HYBRID_BRIDGE_TEXTURE_ORCHESTRATOR_EPILOGUE,
    VF2_HYBRID_BRIDGE_SECOND_SCHEDULER_ENTRY,
    VF2_HYBRID_BRIDGE_CAMERA_BIT7_INTERPRETER,
    VF2_HYBRID_BRIDGE_TEXTURE_SELECTOR_INTERPRETER,
    VF2_HYBRID_BRIDGE_TEXTURE_COUNTER_INTERPRETER,
    VF2_HYBRID_BRIDGE_SECOND_SCHEDULER_WRAPPER_INTERPRETER,
    VF2_HYBRID_BRIDGE_TEXTURE_DECODER_CONTINUATION_INTERPRETER,
    VF2_HYBRID_BRIDGE_RETURN_STUB,
    VF2_HYBRID_BRIDGE_COUNT
} vf2_hybrid_bridge_kind;

typedef struct vf2_hybrid_bridge_report {
    vf2_hybrid_bridge_kind kind;
    uint32_t entry_address;
    uint32_t exit_address;
    uint64_t iterations;
    uint64_t rows;
    uint64_t changed_values;
    size_t bytes_written;
    uint32_t max_recursion_depth;
    uint64_t recovered_instruction_count;
    uint64_t recovered_procedure_calls;
    uint64_t recovered_procedure_returns;
    int cpu_poststate_applied;
} vf2_hybrid_bridge_report;

/* Execute one accepted post-scheduler texture bridge block in recovered C.
 * The current IP selects a complete byte/word decoder, symbol/pair table
 * builder, bounded inner run, recursive expansion or color-conversion
 * procedure. Both memory and architectural CPU state are advanced without
 * copying state from the reference interpreter. */
vf2_status vf2_hybrid_post_frame_bridge_execute(
    vf2_model2a *machine,
    vf2_i960_cpu *cpu,
    vf2_hybrid_bridge_report *report
);

const char *vf2_hybrid_bridge_kind_name(vf2_hybrid_bridge_kind kind);

#endif
